spring.application.name=PetAdoptionSuppliesApplication

spring.datasource.url=jdbc:mysql://localhost:3306/pet_adoption_supplies
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.enabled=true
jwt.secret=yourSecretKey
